# Generated by Django 5.2 on 2025-04-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
