# Generated by Django 5.2 on 2025-04-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_center', '0002_post_meta_description_post_meta_title_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_views',
            field=models.IntegerField(default=0),
        ),
    ]
